server:
  port: 8080
  servlet:
    context-path: /api

spring:
  profiles:
    active: #redis
  application:
    name: bucket-api
  main:
    allow-bean-definition-overriding: true
    allow-circular-references: true
  servlet:
    multipart:
      enabled: true
      max-file-size: 25MB
      max-request-size: 101MB
      file-size-threshold: 2KB
  jpa:
    open-in-view: false
    generate-ddl: true
    show-sql: false
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
        event:
          merge:
            entity_copy_observer: allow
        format_sql: true
    hibernate:
      ddl-auto: update
  flyway:
    enabled: false
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://34.124.255.217:5431/metabucket_dev?useUnicode=yes&characterEncoding=UTF-8
    username: postgres
    password: mysecretpassword
    hikari:
      connectionTimeout: 30000
      minimumIdle: 1
      maximumPoolSize: 50
      idleTimeout: 600000
      maxLifetime: 1800000
      autoCommit: true
      leakDetectionThreshold: 10000
      poolName: bucketConnectionPool

logging:
  level:
    org:
      springframework: INFO
      hibernate:
        SQL: INFO
    org.springframework.security: INFO

security:
  request-log: true
  permit-all-for-dev: true #only open for dev purpose
  cors:
    enabled: false
  jwt:
    secret: v9y$B&E)H@MbQeThWmZq4t7w!z%C*F-JaNdRfUjXn2r775u8x/A?D(G+KbPeShVkYp
    expire-in-minutes: 3000
    issuer: ibrave
    audience: metabucket

base-url:
  confirm-register: metabucket-uat-api.trustdatas.com/api/auth/confirm-register/
  recover-password: metabucket-uat-api.trustdatas.com/api/auth/recover-password/