server:
  port: 8080
  servlet:
    context-path: /api

spring:
  profiles:
    active: ehcache,postgresql-dev
  application:
    name: bucket-api
  main:
    allow-bean-definition-overriding: true
    allow-circular-references: true
  servlet:
    multipart:
      enabled: true
      max-file-size: 25MB
      max-request-size: 101MB
      file-size-threshold: 2KB

logging:
  level:
    org:
      springframework: INFO
      hibernate:
        SQL: INFO
    org.springframework.security: INFO

security:
  request-log: true
  permit-all-for-dev: false #only open for dev purpose
  cors:
    enabled: false
  jwt:
    secret: v9y$B&E)H@MbQeThWmZq4t7w!z%C*F-JaNdRfUjXn2r775u8x/A?D(G+KbPeShVkYp
    expire-in-minutes: 3000
    issuer: ibrave
    audience: metabucket
  default-pwd: abcd@1234

base-url:
  confirm-register: https://metabucket-uat.trustdatas.com/auth/register
  recover-password: https://metabucket-uat.trustdatas.com/reset-password

file:
  dir:
    import-result: import-result/

integration:
  google:
    client-id: 1037815302930-ub1ai3bcld16quurv7bpktipc1gnkm8b.apps.googleusercontent.com
    secret-id: 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
    token-server: https://www.googleapis.com/oauth2/v3/token
